### ISSUE TITLE
Security issues with outdated dependency

### ISSUE THREAD

**Issue by joshrickert** [IBM-Cloud/gp-js-client#121]
`swagger-client@3.3.1` is vulnerable to multiple security holes.

- https://nodesecurity.io/advisories/612
- https://nodesecurity.io/advisories/577

They put out a new release last week to address the first problem. The second should be also resolved in the latest version due to use of the addition caret on the lodash dependency, but a fresh lockfile might be necessary.

**Comment by srl295** [comment]
Yes, i thought they were mostly in dev dependencies. Anyway, I have a new lockfile in the wings.

**Comment by srl295** [comment]
@joshrickert I have published `g11n-pipeline@3.0.1` (and as a backport `g11n-pipeline@2.0.6`) with this dependency updated.
