### ISSUE TITLE
require Node v8+ ? 

### ISSUE THREAD

**Issue by srl295** [IBM-Cloud/gp-js-client#124]
- I've become a fan of async/await, but this means leaving Node 6 behind.
- For now, v2.x of this SDK supports Node ≥4 and v3.0.1+ requires Node ≥8.  (Technically ≥7.10.x)
- If there's interest, I can look into adding transpiling. (and figuring out what that means…)

**Comment by srl295** [comment]
I'm not planning to remove callback APIs from functions that already have them (so no breaking existing code.)  But, I'm planning to not _add_ new APIs that can use callbacks. The APIs will be marked properly.

See also #84  and #86

**Comment by raymondfeng** [comment]
FYI: [strong-globalize](https://github.com/strongloop/strong-globalize) has been rewritten in TypeScript. Now `g11n-pipeline` is only a dependency for our CLI: https://github.com/strongloop/strong-globalize/blob/master/packages/cli/package.json.

**Comment by srl295** [comment]
@raymondfeng From the package.json it seems the CLI already requires Node 8? Then may I won't try to support earlier Nodes in GP

**Comment by srl295** [comment]
OK. we will require node 8.

Calling this: Fixed in #126
