### ISSUE TITLE
Broken headers when using gp client from browser

### ISSUE THREAD

**Issue by jugu** [IBM-Cloud/gp-js-client#128]
Response Headers has: 
`Access-Control-Allow-Headers: x-requested-with, Content-Type, api-key, Authorization`

Since `Date` is not allowed header, we get 
Error: [g11n-pipeline@localhost]: 400:Bad Request Missing 'GP-Date' header value necessary for Globalization Pipeline HMAC.
    at Object.RESTError (site.js:21677)
    at verifyError (site.js:21651)
    at run (site.js:12056)
    at site.js:12073
    at MutationObserver.flush (site.js:11200)

**Comment by srl295** [comment]
Bug is in the REST server.  But, gp-js-client ought to test this case.

**Comment by srl295** [comment]
Fixed in #129
